version: "3"
services:
    nodejs-server:
        container_name: "nodejs-server"
        build: ./backend
        ports: 
            - "8080:8080"

    react-app:
        container_name: "react-app"
        build: ./frontend
        ports: 
            - "8081:8081"
        links: 
            - "nodejs-server"