version: "3"
services:
    nginx-reverse-proxy:
        container_name: "nginx-reverse-proxy"
        restart: always
        build: ./nginx
        ports:
            - "80:80"
        networks: 
            - backend

    nodejs-server:
        container_name: "nodejs-server"
        build: ./backend
        ports: 
            - "8080:8080"
        networks: 
            - backend

    react-app:
        container_name: "react-app"
        build: ./frontend
        ports: 
            - "8081:8081"
        links: 
            - "nodejs-server"
        networks: 
            - backend

networks: 
    backend:
        driver: bridge